# Generated by Django 4.2.7 on 2023-11-27 16:55

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('munroapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='title',
            new_name='hillname',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='description',
        ),
        migrations.AddField(
            model_name='weather',
            name='date',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='feelsLike',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='maxTemp',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='minTemp',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='time',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='weather',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
    ]
