# Generated by Django 4.2.7 on 2023-11-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munroapp', '0002_rename_title_weather_hillname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='hillId',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
