# Generated by Django 4.2.7 on 2023-11-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munroapp', '0003_weather_hillid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Munro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hillId', models.IntegerField()),
                ('hillname', models.CharField(max_length=120)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('metres', models.FloatField()),
            ],
        ),
    ]
