# Generated by Django 4.2.7 on 2023-12-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munroapp', '0005_munro_weatherurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='munro',
            old_name='weatherUrl',
            new_name='weather',
        ),
        migrations.AddField(
            model_name='munro',
            name='county',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='munro',
            name='meaning',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='munro',
            name='nearestWeatherIndex',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
