# Generated by Django 4.2.7 on 2023-12-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munroapp', '0006_rename_weatherurl_munro_weather_munro_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='munro',
            name='nearestWeatherIndex',
        ),
        migrations.RemoveField(
            model_name='munro',
            name='weather',
        ),
        migrations.AddField(
            model_name='munro',
            name='startPointLatitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='munro',
            name='startPointLongitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
