# Generated by Django 4.2.7 on 2023-12-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('munroapp', '0008_climb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climb',
            old_name='date',
            new_name='dateClimbed',
        ),
    ]
