# Generated by Django 4.2.7 on 2023-12-20 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('munroapp', '0009_rename_date_climb_dateclimbed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('dateClimbed', models.DateField()),
                ('munros', models.ManyToManyField(to='munroapp.munro')),
                ('taggedUsers', models.ManyToManyField(related_name='taggedUserToUser', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
