# Generated by Django 4.2.7 on 2023-12-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munroapp', '0011_rename_taggedusers_activity_tagged_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
