# Generated by Django 4.2.7 on 2024-01-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munroapp', '0017_profilephoto_date_added_alter_profilephoto_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='activity_photos/')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='photos',
            field=models.ManyToManyField(blank=True, to='munroapp.activityphoto'),
        ),
    ]
