# Generated by Django 4.2.7 on 2024-01-02 21:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('munroapp', '0018_activityphoto_activity_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='photos',
        ),
        migrations.AddField(
            model_name='activityphoto',
            name='activityId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='munroapp.activity'),
        ),
        migrations.AddField(
            model_name='activityphoto',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
