# Generated by Django 4.2.7 on 2024-01-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munroapp', '0019_remove_activity_photos_activityphoto_activityid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
