# Generated by Django 4.2.7 on 2023-12-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='date_of_birth',
            field=models.DateField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
