# Generated by Django 4.2.7 on 2023-12-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useraccount_date_of_birth_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='home_latitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='home_longitude',
            field=models.FloatField(default=None, null=True),
        ),
    ]
